_format_version: "1.1"

services:
  - name: user-service
    url: http://user-service:8080
    routes:
      - name: user-service-route
        paths:
          - /user-service
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - Authorization
            - Host
            - Origin
            - Referer
            - User-Agent
            - X-Requested-With
          exposed_headers:
            - X-Request-ID
          credentials: true
          max_age: 3600

  - name: diary-service
    url: http://diary-service:8080
    routes:
      - name: diary-service-route
        paths:
          - /diary-service
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - Authorization
            - Host
            - Origin
            - Referer
            - User-Agent
            - X-Requested-With
          exposed_headers:
            - X-Request-ID
          credentials: true
          max_age: 3600

  - name: matching-service
    url: http://matching-service:8080
    routes:
      - name: matching-service-route
        paths:
          - /matching-service
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - Authorization
            - Host
            - Origin
            - Referer
            - User-Agent
            - X-Requested-With
          exposed_headers:
            - X-Request-ID
          credentials: true
          max_age: 3600

plugins:
  - name: prometheus